Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using ZeyadRagyWebExam.Data;
using ZeyadRagyWebExam.Models;

namespace ZeyadRagyWebExam.Controllers
{
    public class JobController : Controller
    {
        public TaskManagementContext connection = new TaskManagementContext();
        public IActionResult Index()
        {
            var res = connection.Jobs.ToList();
            return View(res);
        }
        [HttpPost]
        public IActionResult Create(Job job)
        {
            var res = connection.Jobs.Add(job);
            connection.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Delete(int id, Job job)
        {
            var res = connection.Jobs.Where(jo => jo.Id == id).FirstOrDefault();
            connection.Remove(res);
            connection.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var res = connection.Jobs.Where(jo => jo.Id == id).FirstOrDefault();
            return View(res);
        }
        [HttpPost]
        public IActionResult Edit(int id, Job job)
        {
            var res = connection.Jobs.Where(jo => jo.Id == id).FirstOrDefault();
            res.Status = job.Status;
            connection.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using ZeyadRagyWebExam.Data;
using ZeyadRagyWebExam.Models;

namespace ZeyadRagyWebExam.Controllers
{
    public class ProjectController : Controller
    {
        public TaskManagementContext connection = new TaskManagementContext();
        public IActionResult Index()
        {
            var res= connection.Projects.ToList();
            return View(res);
        }
        [HttpPost]
        public IActionResult Create(Project project)
        {
            var res = connection.Projects.Add(project);
            connection.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]

        public IActionResult Delete(int id,Project project)
        {
           var res = connection.Projects.Where(pro => pro.Id == id).FirstOrDefault();
           connection.Remove(res);
           connection.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
           var res = connection.Projects.Where(pro => pro.Id == id).FirstOrDefault();
           return View(res);
        }
        [HttpPost]
        public IActionResult Edit(int id ,Project project)
        {
            if (ModelState.IsValid)
            {
                var res = connection.Projects.Where(pro => pro.Id == id).FirstOrDefault();
                res.Name = project.Name;
                res.Description = project.Description;
                res.StartDate = project.StartDate;
                res.EndDate = project.EndDate;
                connection.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]

        public IActionResult View(int id) {
            var res = connection.Jobs.Where(jo => jo.ProjectId == id).ToList();
            return View(res);
        }
    }
}

Controllers/TeamMemberController.cs
using Microsoft.AspNetCore.Mvc;
using ZeyadRagyWebExam.Data;
using ZeyadRagyWebExam.Models;

namespace ZeyadRagyWebExam.Controllers
{
    public class TeamMemberController : Controller
    {
        public TaskManagementContext connection = new TaskManagementContext();
        public IActionResult Index()
        {
            var res = connection.TeamMembers.ToList();
            return View(res);
        }
        [HttpPost]
        public IActionResult Create(TeamMember teamMember)
        {
            var res = connection.TeamMembers.Add(teamMember);
            connection.SaveChanges(); 
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id, TeamMember team)
        {
            var res = connection.TeamMembers.Where(team => team.Id == id).FirstOrDefault();
            connection.Remove(res);
            connection.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var res = connection.TeamMembers.Where(team => team.Id == id).FirstOrDefault();
            return View(res);
        }
        [HttpPost]
        public IActionResult Edit(int id, TeamMember teamMember)
        {
            var res = connection.TeamMembers.Where(team => team.Id == id).FirstOrDefault();
            res.Name = teamMember.Name;
            res.Email = teamMember.Email;
            res.Role = teamMember.Role;
            connection.SaveChanges();
            return RedirectToAction("Index");
        }

                [HttpPost]

        public IActionResult View(int id) {
            var res = connection.Jobs.Where(jo => jo.TeamMemberId == id).ToList();
            return View(res);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZeyadRagyWebExam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZeyadRagyWebExam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZeyadRagyWebExam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Job</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeamMember" asp-action="Index">TeamMember</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ZeyadRagyWebExam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>